FROM node:14-alpine as build

COPY package*.json /app/

WORKDIR /app

RUN npm install

COPY . /app

ENV PORT 80
ENV REACT_APP_BE_DOMAIN "http://18.141.55.5"

EXPOSE $PORT
# create optimized codes in folder /app/build
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g",  "daemon off;"]
